# Generated by Django 5.1.2 on 2024-11-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_mail', models.EmailField(max_length=30)),
                ('emp_city', models.CharField(max_length=10)),
            ],
        ),
    ]
