# Generated by Django 5.1.2 on 2024-11-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='emp_id',
            field=models.IntegerField(default=0),
        ),
    ]
