# Generated by Django 5.1.2 on 2024-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0002_data_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='emp_id',
            field=models.IntegerField(),
        ),
    ]
