# Generated by Django 5.1.2 on 2024-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0003_alter_data_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='emp_id',
            field=models.IntegerField(default=0),
        ),
    ]
