# Generated by Django 5.1.2 on 2024-11-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0004_alter_data_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='emp_id',
            field=models.IntegerField(),
        ),
    ]
